### ISSUE TITLE
New primitive: matrix:is-matrix?

### ISSUE THREAD

**Issue by lrq3000** [NetLogo/Matrix-Extension#11]
There should be a primitive to check if a data structure is a matrix, because at the moment, the only way is to first check for any other possibility (scalar, list, etc.) and then by eliminitation, in the else we put instructions in case it's a matrix.

Concrete example:

    ; Deep recursive copy of a megamatrix (list of matrix)
    to-report matrix:copy-recursive [megamatrix]
      ; Entry point: if it's a list, we will recursively copy everything inside (deep copy)
      ifelse is-list? megamatrix [
        let n (length megamatrix)
        let m2 (n-values n [0])

        let i 0
        while [i < n] [
          set m2 (replace-item i m2 (matrix:copy-recursive (item i megamatrix)))
          set i (i + 1)
        ]
        report m2
      ]
      ; Recursively called from here
      [
        ; If it's a number or string we just report it
        ifelse is-number? megamatrix or is-string? megamatrix [
          report  megamatrix
        ]
        ; Else if it's a matrix (we have no other way to check it but by default), then we make a copy and report it
        [
          report matrix:copy megamatrix
        ]
      ]
    end

**Comment by SethTisue** [comment]
agree

**Comment by qiemem** [comment]
Good suggestion. Added.
