### ISSUE TITLE
Bug: matrix:times-scalar tamper the first input matrix

### ISSUE THREAD

**Issue by lrq3000** [NetLogo/Matrix-Extension#12]
There is a bug since NetLogo 5.1 (it doesn't happen in NetLogo 5.0.5) with matrix:times-scalar.

This command not only returns the resulting matrix, but it also modify the first matrix in input. This issue doesn't happen with matrix:times (which gives the correct answer but isn't retrocompatible with NetLogo 5.0.5 because it didn't accept a scalar at the time), and in addition matrix:times-scalar is defined as a reporter, not just a procedure, which makes it weird that it tampers the input.

Here's a code snippet to show the behavior (can be executed directly inside the Command Center):

    (let m matrix:from-row-list [[1 2 3] [4 5 6]]) (let m2 (matrix:times-scalar m -1)) (print m) (print m2)

Result on NetLogo 5.0.5 (correct: the first matrix should be the same as the defined m without any change):

    {{matrix:  [ [ 1 2 3 ][ 4 5 6 ] ]}}
    {{matrix:  [ [ -1 -2 -3 ][ -4 -5 -6 ] ]}}

Result on NetLogo 5.1 and 5.2RC3 (wrong):

    {{matrix:  [ [ -1 -2 -3 ][ -4 -5 -6 ] ]}}
    {{matrix:  [ [ -1 -2 -3 ][ -4 -5 -6 ] ]}}

I have tested all other operators this way but only matrix:times-scalar seems to be affected (I only tried with plus,plus-scalar,times,*, etc... not eigenvalues, det and similar component determinants operations).

May be related to this issue:
http://stackoverflow.com/questions/27928926/weird-netlogo-behavoir-with-big-agentset-and-matrix-extension

**Comment by SethTisue** [comment]
@qiemem, your dept, I think?

**Comment by qiemem** [comment]
Good catch @lrq3000! I went ahead and fixed this. Note that, as the [documentation says](http://ccl.northwestern.edu/netlogo/docs/matrix.html#matrix:times-scalar), `matrix:times-scalar` is now obsolete due to `matrix:times` now allowing both scalars and matrices.

**Comment by lrq3000** [comment]
Thank's @qiemem for fixing this :) I know that times can do it, but I still use times-scalar for two reasons: to keep compatible with older releases of NetLogo and the Matrix extension, and also because it should notify me if something goes wrong in my computation (such as the matrix being multiplied to another matrix instead of a scalar, which I don't want).

On the subject, will matrix:times-scalar be deprecated and removed in future releases or will it stay available as an alias to times?

**Comment by lrq3000** [comment]
PS: there's a typo in the commit in the test.txt: times-scala instead of times-scalar

https://github.com/NetLogo/Matrix-Extension/commit/7b5c6c1f085fce6d61cca9a1267e7d44978a72cf#diff-bcef80de3294eeacd9d425876a2c7820R21

**Comment by SethTisue** [comment]
reopening the bug because of the bad test

**Comment by SethTisue** [comment]
I pushed some new commits on master that make Travis-CI run the tests, to avoid mistakes like this; the build with the failure is https://travis-ci.org/NetLogo/Matrix-Extension/builds/57199079

**Comment by qiemem** [comment]
Thanks Seth. *sigh* I confess, I didn't actually run the language tests (just tested in NetLogo itself).

**Comment by qiemem** [comment]
> On the subject, will `matrix:times-scalar` be deprecated and removed in future releases or will it stay available as an alias to times?

I don't see a strong reason to remove, especially since some users (such as yourself) may find it useful for basic implicit type-checking and may find it more clearly expresses intention.

**Comment by lrq3000** [comment]
Ok thank's for the info :)

**Comment by qiemem** [comment]
Fixed the test.
